---
- name: Docker redis prepare ext
  hosts: all
  become: true

  tasks:
    - name: Mkdir dirs
      file:
        state: directory
        path: "{{ redis_root_dir }}/{{ item }}"
        mode: 0755
      with_items:
        - compose
        - compose_project

    - name: Copy files
      template:
        src: "{{ item }}"
        dest: "{{ redis_root_dir }}/compose_project/{{ item }}"
        mode: 0644
      with_items:
        - ../compose/docker-compose.yml
        - ../compose/docker-compose.override.yml
        - docker-compose.yml

    - name: Copy scripts
      template:
        src: "{{ item }}"
        dest: "{{ redis_root_dir }}/compose_project/{{ item }}"
        mode: 0755
      with_items:
        - docker-compose.sh

    - name: Add logrotate conf
      template:
        src: "logrotate.j2"
        dest: "/etc/logrotate.d/redis_{{ redis_port }}"
