version: '3'

services:
  redis:
    image: "${REDIS_DOCKER_TAG:-redis:5.0-alpine}"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
    pid: host
    ports:
      - "${REDIS_PORT:-6379}:6379/tcp"
    networks:
      - redis

volumes:
  redis_data:

networks:
  redis:
